[project]
name = "1-learning-programming-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pep8>=1.7.1",
    "pycodestyle>=2.14.0",
    "pythonturtle>=0.3.2",
]
